### ISSUE TITLE
Getting an error that 'a' is not a constructor.

### ISSUE THREAD

**Issue by atlantageek** [w8r/wms-capabilities#29]
With the following code I'm getting an error.

```
import fs from 'fs';
import {fileURLToPath} from 'url';
import path from 'path';
import WMSCapabilities from 'wms-capabilities';

const __filename = fileURLToPath(import.meta.url);

const __dirname = path.dirname(__filename);
console.log('directory-name 👉️', __dirname);

const xml=fs.readFileSync(__dirname + '/foo.xml')
result=new WMSCapabilities(xml).toJSON();
```

The error is
```
TypeError: a is not a constructor
    at new z (/home/atlantageek/dev/gis/experiment/node_modules/wms-capabilities/dist/wms-capabilities.min.js:9:212)
    at new g (/home/atlantageek/dev/gis/experiment/node_modules/wms-capabilities/dist/wms-capabilities.min.js:17:84)
    at file:///home/atlantageek/dev/gis/experiment/bob.js:11:8
```
Any guidance would be appreciated.

**Comment by w8r** [comment]
https://codesandbox.io/s/brave-breeze-tcd9sc?file=/src/index.ts
